import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>majimakart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <nav className={styles.top}>TOP</nav> 
         <nav className={styles.list}>
          <ul className={styles.navlist}>
            <li className={styles.navlistitem}>TODAY</li>
            <li className={styles.navlistitem}>SEASON</li>
          </ul>
         </nav>
      </header>

      <main className={styles.main}>
        <div className={styles.mainFlex}>
          <div className={styles.title}>
            <a href="https://nextjs.org">Majima Kart DX</a>
          </div>
          <div className={styles.score}>
            <table border="1" className={styles.scoreTable}>
              <tr><th>Rate</th></tr>
              <tr><td>セル</td><td>セル</td><td>セル</td></tr>
              <tr><td>セル</td><td>セル</td><td>セル</td></tr>
              <tr><td>セル</td><td>セル</td><td>セル</td></tr>
              <tr><td>セル</td><td>セル</td><td>セル</td></tr>
              <tr><td>セル</td><td>セル</td><td>セル</td></tr>
            </table>
          </div>
        </div>
      </main>

      
    </div>
  )
}
